version: '3.8'
services:
  mongodb:
    image: mongo:7.0.12
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - /Users/shashi/Dockers/MongoDb/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  notes-app:
    build: .
    container_name: notes-app
    depends_on:
      - mongodb