server:
  port: 8080

spring:
  application:
    name: notes-app
  data:
    mongodb:
      host: localhost
      username: root
      password: root
      database: note_app
      port: 27017
      authentication-database: admin


