version: '3.8'

services:
  mongodb:
    image: mongo:7.0.12
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ~/mongo/data:/data/db
      - ./init-scripts:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: notes-app
    command: ["mongod", "--auth"]

